/*
 * This file is generated by jOOQ.
 */
package io.xj.hub;


import org.jooq.Catalog;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Xj extends SchemaImpl {

  private static final long serialVersionUID = 1L;

  /**
   * The reference instance of <code>xj</code>
   */
  public static final Xj XJ = new Xj();

  /**
   * The table <code>xj.account</code>.
   */

  /**
   * No further instances allowed
   */
  private Xj() {
    super("xj", null);
  }


  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }
}
