# Copyright (c) XJ Music Inc. (https://xj.io) All Rights Reserved.

output "xj_prod_cluster_id" {
  description = "EKS cluster ID."
  value       = module.xj-prod-eks.cluster_id
}

output "xj_prod_cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.xj-prod-eks.cluster_endpoint
}

output "xj_prod_cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.xj-prod-eks.cluster_security_group_id
}

output "xj_prod_kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.xj-prod-eks.kubeconfig
}

output "xj_prod_config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.xj-prod-eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = local.aws-region
}

output "xj_prod_cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.xj-prod-cluster-name
}

output "aws_availability_zones" {
  description = "All AWS availability zones based on current region"
  value       = data.aws_availability_zones.available.names
}
