/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import io.xj.hub.enums.InstrumentMode;
import io.xj.hub.enums.InstrumentState;
import io.xj.hub.enums.InstrumentType;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IInstrument extends Serializable {

    /**
     * Setter for <code>xj.instrument.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.instrument.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.instrument.library_id</code>.
     */
    public void setLibraryId(UUID value);

    /**
     * Getter for <code>xj.instrument.library_id</code>.
     */
    public UUID getLibraryId();

    /**
     * Setter for <code>xj.instrument.type</code>.
     */
    public void setType(InstrumentType value);

    /**
     * Getter for <code>xj.instrument.type</code>.
     */
    public InstrumentType getType();

    /**
     * Setter for <code>xj.instrument.state</code>.
     */
    public void setState(InstrumentState value);

    /**
     * Getter for <code>xj.instrument.state</code>.
     */
    public InstrumentState getState();

    /**
     * Setter for <code>xj.instrument.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.instrument.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>xj.instrument.density</code>.
     */
    public void setDensity(Float value);

    /**
     * Getter for <code>xj.instrument.density</code>.
     */
    public Float getDensity();

    /**
     * Setter for <code>xj.instrument.config</code>.
     */
    public void setConfig(String value);

    /**
     * Getter for <code>xj.instrument.config</code>.
     */
    public String getConfig();

    /**
     * Setter for <code>xj.instrument.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value);

    /**
     * Getter for <code>xj.instrument.is_deleted</code>.
     */
    public Boolean getIsDeleted();

    /**
     * Setter for <code>xj.instrument.volume</code>.
     */
    public void setVolume(Float value);

    /**
     * Getter for <code>xj.instrument.volume</code>.
     */
    public Float getVolume();

    /**
     * Setter for <code>xj.instrument.mode</code>.
     */
    public void setMode(InstrumentMode value);

    /**
     * Getter for <code>xj.instrument.mode</code>.
     */
    public InstrumentMode getMode();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IInstrument
     */
    public void from(IInstrument from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IInstrument
     */
    public <E extends IInstrument> E into(E into);
}
