/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import io.xj.hub.enums.ProgramState;
import io.xj.hub.enums.ProgramType;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProgram extends Serializable {

    /**
     * Setter for <code>xj.program.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.program.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.program.library_id</code>.
     */
    public void setLibraryId(UUID value);

    /**
     * Getter for <code>xj.program.library_id</code>.
     */
    public UUID getLibraryId();

    /**
     * Setter for <code>xj.program.state</code>.
     */
    public void setState(ProgramState value);

    /**
     * Getter for <code>xj.program.state</code>.
     */
    public ProgramState getState();

    /**
     * Setter for <code>xj.program.key</code>.
     */
    public void setKey(String value);

    /**
     * Getter for <code>xj.program.key</code>.
     */
    public String getKey();

    /**
     * Setter for <code>xj.program.tempo</code>.
     */
    public void setTempo(Float value);

    /**
     * Getter for <code>xj.program.tempo</code>.
     */
    public Float getTempo();

    /**
     * Setter for <code>xj.program.type</code>.
     */
    public void setType(ProgramType value);

    /**
     * Getter for <code>xj.program.type</code>.
     */
    public ProgramType getType();

    /**
     * Setter for <code>xj.program.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.program.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>xj.program.density</code>.
     */
    public void setDensity(Float value);

    /**
     * Getter for <code>xj.program.density</code>.
     */
    public Float getDensity();

    /**
     * Setter for <code>xj.program.config</code>.
     */
    public void setConfig(String value);

    /**
     * Getter for <code>xj.program.config</code>.
     */
    public String getConfig();

    /**
     * Setter for <code>xj.program.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value);

    /**
     * Getter for <code>xj.program.is_deleted</code>.
     */
    public Boolean getIsDeleted();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IProgram
     */
    public void from(IProgram from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IProgram
     */
    public <E extends IProgram> E into(E into);
}
