/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import io.xj.hub.enums.InstrumentType;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProgramVoice extends Serializable {

    /**
     * Setter for <code>xj.program_voice.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.program_voice.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.program_voice.program_id</code>.
     */
    public void setProgramId(UUID value);

    /**
     * Getter for <code>xj.program_voice.program_id</code>.
     */
    public UUID getProgramId();

    /**
     * Setter for <code>xj.program_voice.type</code>.
     */
    public void setType(InstrumentType value);

    /**
     * Getter for <code>xj.program_voice.type</code>.
     */
    public InstrumentType getType();

    /**
     * Setter for <code>xj.program_voice.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.program_voice.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>xj.program_voice.order</code>.
     */
    public void setOrder(Float value);

    /**
     * Getter for <code>xj.program_voice.order</code>.
     */
    public Float getOrder();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IProgramVoice
     */
    public void from(IProgramVoice from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IProgramVoice
     */
    public <E extends IProgramVoice> E into(E into);
}
