/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProgramSequenceChordVoicing extends Serializable {

    /**
     * Setter for <code>xj.program_sequence_chord_voicing.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_chord_voicing.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.program_sequence_chord_voicing.program_id</code>.
     */
    public void setProgramId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_chord_voicing.program_id</code>.
     */
    public UUID getProgramId();

    /**
     * Setter for
     * <code>xj.program_sequence_chord_voicing.program_sequence_chord_id</code>.
     */
    public void setProgramSequenceChordId(UUID value);

    /**
     * Getter for
     * <code>xj.program_sequence_chord_voicing.program_sequence_chord_id</code>.
     */
    public UUID getProgramSequenceChordId();

    /**
     * Setter for <code>xj.program_sequence_chord_voicing.notes</code>.
     */
    public void setNotes(String value);

    /**
     * Getter for <code>xj.program_sequence_chord_voicing.notes</code>.
     */
    public String getNotes();

    /**
     * Setter for
     * <code>xj.program_sequence_chord_voicing.program_voice_id</code>.
     */
    public void setProgramVoiceId(UUID value);

    /**
     * Getter for
     * <code>xj.program_sequence_chord_voicing.program_voice_id</code>.
     */
    public UUID getProgramVoiceId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IProgramSequenceChordVoicing
     */
    public void from(IProgramSequenceChordVoicing from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IProgramSequenceChordVoicing
     */
    public <E extends IProgramSequenceChordVoicing> E into(E into);
}
