/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import io.xj.hub.enums.TemplateType;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITemplate extends Serializable {

    /**
     * Setter for <code>xj.template.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.template.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.template.account_id</code>.
     */
    public void setAccountId(UUID value);

    /**
     * Getter for <code>xj.template.account_id</code>.
     */
    public UUID getAccountId();

    /**
     * Setter for <code>xj.template.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.template.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>xj.template.config</code>.
     */
    public void setConfig(String value);

    /**
     * Getter for <code>xj.template.config</code>.
     */
    public String getConfig();

    /**
     * Setter for <code>xj.template.ship_key</code>.
     */
    public void setShipKey(String value);

    /**
     * Getter for <code>xj.template.ship_key</code>.
     */
    public String getShipKey();

    /**
     * Setter for <code>xj.template.type</code>.
     */
    public void setType(TemplateType value);

    /**
     * Getter for <code>xj.template.type</code>.
     */
    public TemplateType getType();

    /**
     * Setter for <code>xj.template.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value);

    /**
     * Getter for <code>xj.template.is_deleted</code>.
     */
    public Boolean getIsDeleted();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ITemplate
     */
    public void from(ITemplate from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ITemplate
     */
    public <E extends ITemplate> E into(E into);
}
