/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import io.xj.hub.enums.ContentBindingType;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITemplateBinding extends Serializable {

    /**
     * Setter for <code>xj.template_binding.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.template_binding.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.template_binding.type</code>.
     */
    public void setType(ContentBindingType value);

    /**
     * Getter for <code>xj.template_binding.type</code>.
     */
    public ContentBindingType getType();

    /**
     * Setter for <code>xj.template_binding.template_id</code>.
     */
    public void setTemplateId(UUID value);

    /**
     * Getter for <code>xj.template_binding.template_id</code>.
     */
    public UUID getTemplateId();

    /**
     * Setter for <code>xj.template_binding.target_id</code>.
     */
    public void setTargetId(UUID value);

    /**
     * Getter for <code>xj.template_binding.target_id</code>.
     */
    public UUID getTargetId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ITemplateBinding
     */
    public void from(ITemplateBinding from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ITemplateBinding
     */
    public <E extends ITemplateBinding> E into(E into);
}
