/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import io.xj.hub.enums.UserAuthType;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserAuth extends Serializable {

    /**
     * Setter for <code>xj.user_auth.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.user_auth.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.user_auth.type</code>.
     */
    public void setType(UserAuthType value);

    /**
     * Getter for <code>xj.user_auth.type</code>.
     */
    public UserAuthType getType();

    /**
     * Setter for <code>xj.user_auth.external_access_token</code>.
     */
    public void setExternalAccessToken(String value);

    /**
     * Getter for <code>xj.user_auth.external_access_token</code>.
     */
    public String getExternalAccessToken();

    /**
     * Setter for <code>xj.user_auth.external_refresh_token</code>.
     */
    public void setExternalRefreshToken(String value);

    /**
     * Getter for <code>xj.user_auth.external_refresh_token</code>.
     */
    public String getExternalRefreshToken();

    /**
     * Setter for <code>xj.user_auth.external_account</code>.
     */
    public void setExternalAccount(String value);

    /**
     * Getter for <code>xj.user_auth.external_account</code>.
     */
    public String getExternalAccount();

    /**
     * Setter for <code>xj.user_auth.user_id</code>.
     */
    public void setUserId(UUID value);

    /**
     * Getter for <code>xj.user_auth.user_id</code>.
     */
    public UUID getUserId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUserAuth
     */
    public void from(IUserAuth from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUserAuth
     */
    public <E extends IUserAuth> E into(E into);
}
