/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAccountUser extends Serializable {

    /**
     * Setter for <code>xj.account_user.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.account_user.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.account_user.user_id</code>.
     */
    public void setUserId(UUID value);

    /**
     * Getter for <code>xj.account_user.user_id</code>.
     */
    public UUID getUserId();

    /**
     * Setter for <code>xj.account_user.account_id</code>.
     */
    public void setAccountId(UUID value);

    /**
     * Getter for <code>xj.account_user.account_id</code>.
     */
    public UUID getAccountId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IAccountUser
     */
    public void from(IAccountUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IAccountUser
     */
    public <E extends IAccountUser> E into(E into);
}
