/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IInstrumentAudio extends Serializable {

    /**
     * Setter for <code>xj.instrument_audio.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.instrument_audio.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.instrument_audio.instrument_id</code>.
     */
    public void setInstrumentId(UUID value);

    /**
     * Getter for <code>xj.instrument_audio.instrument_id</code>.
     */
    public UUID getInstrumentId();

    /**
     * Setter for <code>xj.instrument_audio.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.instrument_audio.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>xj.instrument_audio.waveform_key</code>.
     */
    public void setWaveformKey(String value);

    /**
     * Getter for <code>xj.instrument_audio.waveform_key</code>.
     */
    public String getWaveformKey();

    /**
     * Setter for <code>xj.instrument_audio.transient_seconds</code>.
     */
    public void setTransientSeconds(Float value);

    /**
     * Getter for <code>xj.instrument_audio.transient_seconds</code>.
     */
    public Float getTransientSeconds();

    /**
     * Setter for <code>xj.instrument_audio.total_beats</code>.
     */
    public void setTotalBeats(Float value);

    /**
     * Getter for <code>xj.instrument_audio.total_beats</code>.
     */
    public Float getTotalBeats();

    /**
     * Setter for <code>xj.instrument_audio.tempo</code>.
     */
    public void setTempo(Float value);

    /**
     * Getter for <code>xj.instrument_audio.tempo</code>.
     */
    public Float getTempo();

    /**
     * Setter for <code>xj.instrument_audio.density</code>.
     */
    public void setDensity(Float value);

    /**
     * Getter for <code>xj.instrument_audio.density</code>.
     */
    public Float getDensity();

    /**
     * Setter for <code>xj.instrument_audio.event</code>.
     */
    public void setEvent(String value);

    /**
     * Getter for <code>xj.instrument_audio.event</code>.
     */
    public String getEvent();

    /**
     * Setter for <code>xj.instrument_audio.volume</code>.
     */
    public void setVolume(Float value);

    /**
     * Getter for <code>xj.instrument_audio.volume</code>.
     */
    public Float getVolume();

    /**
     * Setter for <code>xj.instrument_audio.tones</code>.
     */
    public void setTones(String value);

    /**
     * Getter for <code>xj.instrument_audio.tones</code>.
     */
    public String getTones();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IInstrumentAudio
     */
    public void from(IInstrumentAudio from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IInstrumentAudio
     */
    public <E extends IInstrumentAudio> E into(E into);
}
