/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IInstrumentMeme extends Serializable {

    /**
     * Setter for <code>xj.instrument_meme.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.instrument_meme.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.instrument_meme.instrument_id</code>.
     */
    public void setInstrumentId(UUID value);

    /**
     * Getter for <code>xj.instrument_meme.instrument_id</code>.
     */
    public UUID getInstrumentId();

    /**
     * Setter for <code>xj.instrument_meme.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.instrument_meme.name</code>.
     */
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IInstrumentMeme
     */
    public void from(IInstrumentMeme from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IInstrumentMeme
     */
    public <E extends IInstrumentMeme> E into(E into);
}
