/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProgramSequence extends Serializable {

    /**
     * Setter for <code>xj.program_sequence.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.program_sequence.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.program_sequence.program_id</code>.
     */
    public void setProgramId(UUID value);

    /**
     * Getter for <code>xj.program_sequence.program_id</code>.
     */
    public UUID getProgramId();

    /**
     * Setter for <code>xj.program_sequence.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.program_sequence.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>xj.program_sequence.key</code>.
     */
    public void setKey(String value);

    /**
     * Getter for <code>xj.program_sequence.key</code>.
     */
    public String getKey();

    /**
     * Setter for <code>xj.program_sequence.density</code>.
     */
    public void setDensity(Float value);

    /**
     * Getter for <code>xj.program_sequence.density</code>.
     */
    public Float getDensity();

    /**
     * Setter for <code>xj.program_sequence.total</code>.
     */
    public void setTotal(Short value);

    /**
     * Getter for <code>xj.program_sequence.total</code>.
     */
    public Short getTotal();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IProgramSequence
     */
    public void from(IProgramSequence from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IProgramSequence
     */
    public <E extends IProgramSequence> E into(E into);
}
