/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProgramVoiceTrack extends Serializable {

    /**
     * Setter for <code>xj.program_voice_track.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.program_voice_track.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.program_voice_track.program_id</code>.
     */
    public void setProgramId(UUID value);

    /**
     * Getter for <code>xj.program_voice_track.program_id</code>.
     */
    public UUID getProgramId();

    /**
     * Setter for <code>xj.program_voice_track.program_voice_id</code>.
     */
    public void setProgramVoiceId(UUID value);

    /**
     * Getter for <code>xj.program_voice_track.program_voice_id</code>.
     */
    public UUID getProgramVoiceId();

    /**
     * Setter for <code>xj.program_voice_track.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.program_voice_track.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>xj.program_voice_track.order</code>.
     */
    public void setOrder(Float value);

    /**
     * Getter for <code>xj.program_voice_track.order</code>.
     */
    public Float getOrder();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IProgramVoiceTrack
     */
    public void from(IProgramVoiceTrack from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IProgramVoiceTrack
     */
    public <E extends IProgramVoiceTrack> E into(E into);
}
