/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProgramMeme extends Serializable {

    /**
     * Setter for <code>xj.program_meme.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.program_meme.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.program_meme.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.program_meme.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>xj.program_meme.program_id</code>.
     */
    public void setProgramId(UUID value);

    /**
     * Getter for <code>xj.program_meme.program_id</code>.
     */
    public UUID getProgramId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IProgramMeme
     */
    public void from(IProgramMeme from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IProgramMeme
     */
    public <E extends IProgramMeme> E into(E into);
}
