/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProgramSequencePattern extends Serializable {

    /**
     * Setter for <code>xj.program_sequence_pattern.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_pattern.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.program_sequence_pattern.program_id</code>.
     */
    public void setProgramId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_pattern.program_id</code>.
     */
    public UUID getProgramId();

    /**
     * Setter for <code>xj.program_sequence_pattern.program_sequence_id</code>.
     */
    public void setProgramSequenceId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_pattern.program_sequence_id</code>.
     */
    public UUID getProgramSequenceId();

    /**
     * Setter for <code>xj.program_sequence_pattern.program_voice_id</code>.
     */
    public void setProgramVoiceId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_pattern.program_voice_id</code>.
     */
    public UUID getProgramVoiceId();

    /**
     * Setter for <code>xj.program_sequence_pattern.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.program_sequence_pattern.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>xj.program_sequence_pattern.total</code>.
     */
    public void setTotal(Short value);

    /**
     * Getter for <code>xj.program_sequence_pattern.total</code>.
     */
    public Short getTotal();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IProgramSequencePattern
     */
    public void from(IProgramSequencePattern from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IProgramSequencePattern
     */
    public <E extends IProgramSequencePattern> E into(E into);
}
