/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProgramSequenceBindingMeme extends Serializable {

    /**
     * Setter for <code>xj.program_sequence_binding_meme.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_binding_meme.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.program_sequence_binding_meme.program_id</code>.
     */
    public void setProgramId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_binding_meme.program_id</code>.
     */
    public UUID getProgramId();

    /**
     * Setter for
     * <code>xj.program_sequence_binding_meme.program_sequence_binding_id</code>.
     */
    public void setProgramSequenceBindingId(UUID value);

    /**
     * Getter for
     * <code>xj.program_sequence_binding_meme.program_sequence_binding_id</code>.
     */
    public UUID getProgramSequenceBindingId();

    /**
     * Setter for <code>xj.program_sequence_binding_meme.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.program_sequence_binding_meme.name</code>.
     */
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IProgramSequenceBindingMeme
     */
    public void from(IProgramSequenceBindingMeme from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IProgramSequenceBindingMeme
     */
    public <E extends IProgramSequenceBindingMeme> E into(E into);
}
