/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProgramSequencePatternEvent extends Serializable {

    /**
     * Setter for <code>xj.program_sequence_pattern_event.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_pattern_event.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.program_sequence_pattern_event.program_id</code>.
     */
    public void setProgramId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_pattern_event.program_id</code>.
     */
    public UUID getProgramId();

    /**
     * Setter for
     * <code>xj.program_sequence_pattern_event.program_sequence_pattern_id</code>.
     */
    public void setProgramSequencePatternId(UUID value);

    /**
     * Getter for
     * <code>xj.program_sequence_pattern_event.program_sequence_pattern_id</code>.
     */
    public UUID getProgramSequencePatternId();

    /**
     * Setter for
     * <code>xj.program_sequence_pattern_event.program_voice_track_id</code>.
     */
    public void setProgramVoiceTrackId(UUID value);

    /**
     * Getter for
     * <code>xj.program_sequence_pattern_event.program_voice_track_id</code>.
     */
    public UUID getProgramVoiceTrackId();

    /**
     * Setter for <code>xj.program_sequence_pattern_event.velocity</code>.
     */
    public void setVelocity(Float value);

    /**
     * Getter for <code>xj.program_sequence_pattern_event.velocity</code>.
     */
    public Float getVelocity();

    /**
     * Setter for <code>xj.program_sequence_pattern_event.position</code>.
     */
    public void setPosition(Float value);

    /**
     * Getter for <code>xj.program_sequence_pattern_event.position</code>.
     */
    public Float getPosition();

    /**
     * Setter for <code>xj.program_sequence_pattern_event.duration</code>.
     */
    public void setDuration(Float value);

    /**
     * Getter for <code>xj.program_sequence_pattern_event.duration</code>.
     */
    public Float getDuration();

    /**
     * Setter for <code>xj.program_sequence_pattern_event.tones</code>.
     */
    public void setTones(String value);

    /**
     * Getter for <code>xj.program_sequence_pattern_event.tones</code>.
     */
    public String getTones();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IProgramSequencePatternEvent
     */
    public void from(IProgramSequencePatternEvent from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IProgramSequencePatternEvent
     */
    public <E extends IProgramSequencePatternEvent> E into(E into);
}
