/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITemplatePlayback extends Serializable {

    /**
     * Setter for <code>xj.template_playback.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.template_playback.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.template_playback.template_id</code>.
     */
    public void setTemplateId(UUID value);

    /**
     * Getter for <code>xj.template_playback.template_id</code>.
     */
    public UUID getTemplateId();

    /**
     * Setter for <code>xj.template_playback.user_id</code>.
     */
    public void setUserId(UUID value);

    /**
     * Getter for <code>xj.template_playback.user_id</code>.
     */
    public UUID getUserId();

    /**
     * Setter for <code>xj.template_playback.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value);

    /**
     * Getter for <code>xj.template_playback.created_at</code>.
     */
    public LocalDateTime getCreatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ITemplatePlayback
     */
    public void from(ITemplatePlayback from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ITemplatePlayback
     */
    public <E extends ITemplatePlayback> E into(E into);
}
