/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.enums;


import io.xj.hub.Xj;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum InstrumentMode implements EnumType {

    Event("Event"),

    Chord("Chord"),

    Loop("Loop"),

    Transition("Transition"),

    Background("Background");

    private final String literal;

    private InstrumentMode(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Xj.XJ;
    }

    @Override
    public String getName() {
        return "instrument_mode";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
