#!/usr/bin/env bash

# Include common functions
. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../cmd/common/core

# Container Arguments
APP=xj
DOCKER_ARGS=$@

# assumes run from the xj folder
BASE="${PWD}"
NAME="${APP}01"
TAG="run_${APP}"

#
ensure_no_docker_named ${NAME}

#
step "docker build tag[${TAG}] name[${NAME}]"
docker build \
    -t ${TAG} \
    . || exit 1
step_ok

#
finished_ok

