/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.tables.interfaces.IAccount;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements IAccount {

    private static final long serialVersionUID = 1L;

    private UUID   id;
    private String name;

    public Account() {}

    public Account(IAccount value) {
        this.id = value.getId();
        this.name = value.getName();
    }

    public Account(
        UUID   id,
        String name
    ) {
        this.id = id;
        this.name = name;
    }

    /**
     * Getter for <code>xj.account.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.account.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.account.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>xj.account.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAccount from) {
        setId(from.getId());
        setName(from.getName());
    }

    @Override
    public <E extends IAccount> E into(E into) {
        into.from(this);
        return into;
    }
}
