/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.tables.interfaces.ILibrary;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Library implements ILibrary {

    private static final long serialVersionUID = 1L;

    private UUID    id;
    private String  name;
    private UUID    accountId;
    private Boolean isDeleted;

    public Library() {}

    public Library(ILibrary value) {
        this.id = value.getId();
        this.name = value.getName();
        this.accountId = value.getAccountId();
        this.isDeleted = value.getIsDeleted();
    }

    public Library(
        UUID    id,
        String  name,
        UUID    accountId,
        Boolean isDeleted
    ) {
        this.id = id;
        this.name = name;
        this.accountId = accountId;
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>xj.library.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.library.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.library.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>xj.library.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>xj.library.account_id</code>.
     */
    @Override
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>xj.library.account_id</code>.
     */
    @Override
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>xj.library.is_deleted</code>.
     */
    @Override
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>xj.library.is_deleted</code>.
     */
    @Override
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Library (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(accountId);
        sb.append(", ").append(isDeleted);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ILibrary from) {
        setId(from.getId());
        setName(from.getName());
        setAccountId(from.getAccountId());
        setIsDeleted(from.getIsDeleted());
    }

    @Override
    public <E extends ILibrary> E into(E into) {
        into.from(this);
        return into;
    }
}
