/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.enums.ProgramState;
import io.xj.hub.enums.ProgramType;
import io.xj.hub.tables.interfaces.IProgram;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Program implements IProgram {

    private static final long serialVersionUID = 1L;

    private UUID         id;
    private UUID         libraryId;
    private ProgramState state;
    private String       key;
    private Float        tempo;
    private ProgramType  type;
    private String       name;
    private Float        density;
    private String       config;
    private Boolean      isDeleted;

    public Program() {}

    public Program(IProgram value) {
        this.id = value.getId();
        this.libraryId = value.getLibraryId();
        this.state = value.getState();
        this.key = value.getKey();
        this.tempo = value.getTempo();
        this.type = value.getType();
        this.name = value.getName();
        this.density = value.getDensity();
        this.config = value.getConfig();
        this.isDeleted = value.getIsDeleted();
    }

    public Program(
        UUID         id,
        UUID         libraryId,
        ProgramState state,
        String       key,
        Float        tempo,
        ProgramType  type,
        String       name,
        Float        density,
        String       config,
        Boolean      isDeleted
    ) {
        this.id = id;
        this.libraryId = libraryId;
        this.state = state;
        this.key = key;
        this.tempo = tempo;
        this.type = type;
        this.name = name;
        this.density = density;
        this.config = config;
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>xj.program.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.program.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.program.library_id</code>.
     */
    @Override
    public UUID getLibraryId() {
        return this.libraryId;
    }

    /**
     * Setter for <code>xj.program.library_id</code>.
     */
    @Override
    public void setLibraryId(UUID libraryId) {
        this.libraryId = libraryId;
    }

    /**
     * Getter for <code>xj.program.state</code>.
     */
    @Override
    public ProgramState getState() {
        return this.state;
    }

    /**
     * Setter for <code>xj.program.state</code>.
     */
    @Override
    public void setState(ProgramState state) {
        this.state = state;
    }

    /**
     * Getter for <code>xj.program.key</code>.
     */
    @Override
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>xj.program.key</code>.
     */
    @Override
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for <code>xj.program.tempo</code>.
     */
    @Override
    public Float getTempo() {
        return this.tempo;
    }

    /**
     * Setter for <code>xj.program.tempo</code>.
     */
    @Override
    public void setTempo(Float tempo) {
        this.tempo = tempo;
    }

    /**
     * Getter for <code>xj.program.type</code>.
     */
    @Override
    public ProgramType getType() {
        return this.type;
    }

    /**
     * Setter for <code>xj.program.type</code>.
     */
    @Override
    public void setType(ProgramType type) {
        this.type = type;
    }

    /**
     * Getter for <code>xj.program.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>xj.program.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>xj.program.density</code>.
     */
    @Override
    public Float getDensity() {
        return this.density;
    }

    /**
     * Setter for <code>xj.program.density</code>.
     */
    @Override
    public void setDensity(Float density) {
        this.density = density;
    }

    /**
     * Getter for <code>xj.program.config</code>.
     */
    @Override
    public String getConfig() {
        return this.config;
    }

    /**
     * Setter for <code>xj.program.config</code>.
     */
    @Override
    public void setConfig(String config) {
        this.config = config;
    }

    /**
     * Getter for <code>xj.program.is_deleted</code>.
     */
    @Override
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>xj.program.is_deleted</code>.
     */
    @Override
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Program (");

        sb.append(id);
        sb.append(", ").append(libraryId);
        sb.append(", ").append(state);
        sb.append(", ").append(key);
        sb.append(", ").append(tempo);
        sb.append(", ").append(type);
        sb.append(", ").append(name);
        sb.append(", ").append(density);
        sb.append(", ").append(config);
        sb.append(", ").append(isDeleted);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IProgram from) {
        setId(from.getId());
        setLibraryId(from.getLibraryId());
        setState(from.getState());
        setKey(from.getKey());
        setTempo(from.getTempo());
        setType(from.getType());
        setName(from.getName());
        setDensity(from.getDensity());
        setConfig(from.getConfig());
        setIsDeleted(from.getIsDeleted());
    }

    @Override
    public <E extends IProgram> E into(E into) {
        into.from(this);
        return into;
    }
}
