/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.tables.interfaces.IProgramSequenceBindingMeme;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProgramSequenceBindingMeme implements IProgramSequenceBindingMeme {

    private static final long serialVersionUID = 1L;

    private UUID   id;
    private UUID   programId;
    private UUID   programSequenceBindingId;
    private String name;

    public ProgramSequenceBindingMeme() {}

    public ProgramSequenceBindingMeme(IProgramSequenceBindingMeme value) {
        this.id = value.getId();
        this.programId = value.getProgramId();
        this.programSequenceBindingId = value.getProgramSequenceBindingId();
        this.name = value.getName();
    }

    public ProgramSequenceBindingMeme(
        UUID   id,
        UUID   programId,
        UUID   programSequenceBindingId,
        String name
    ) {
        this.id = id;
        this.programId = programId;
        this.programSequenceBindingId = programSequenceBindingId;
        this.name = name;
    }

    /**
     * Getter for <code>xj.program_sequence_binding_meme.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.program_sequence_binding_meme.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.program_sequence_binding_meme.program_id</code>.
     */
    @Override
    public UUID getProgramId() {
        return this.programId;
    }

    /**
     * Setter for <code>xj.program_sequence_binding_meme.program_id</code>.
     */
    @Override
    public void setProgramId(UUID programId) {
        this.programId = programId;
    }

    /**
     * Getter for
     * <code>xj.program_sequence_binding_meme.program_sequence_binding_id</code>.
     */
    @Override
    public UUID getProgramSequenceBindingId() {
        return this.programSequenceBindingId;
    }

    /**
     * Setter for
     * <code>xj.program_sequence_binding_meme.program_sequence_binding_id</code>.
     */
    @Override
    public void setProgramSequenceBindingId(UUID programSequenceBindingId) {
        this.programSequenceBindingId = programSequenceBindingId;
    }

    /**
     * Getter for <code>xj.program_sequence_binding_meme.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>xj.program_sequence_binding_meme.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProgramSequenceBindingMeme (");

        sb.append(id);
        sb.append(", ").append(programId);
        sb.append(", ").append(programSequenceBindingId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IProgramSequenceBindingMeme from) {
        setId(from.getId());
        setProgramId(from.getProgramId());
        setProgramSequenceBindingId(from.getProgramSequenceBindingId());
        setName(from.getName());
    }

    @Override
    public <E extends IProgramSequenceBindingMeme> E into(E into) {
        into.from(this);
        return into;
    }
}
