/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.tables.interfaces.IProgramMeme;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProgramMeme implements IProgramMeme {

    private static final long serialVersionUID = 1L;

    private UUID   id;
    private String name;
    private UUID   programId;

    public ProgramMeme() {}

    public ProgramMeme(IProgramMeme value) {
        this.id = value.getId();
        this.name = value.getName();
        this.programId = value.getProgramId();
    }

    public ProgramMeme(
        UUID   id,
        String name,
        UUID   programId
    ) {
        this.id = id;
        this.name = name;
        this.programId = programId;
    }

    /**
     * Getter for <code>xj.program_meme.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.program_meme.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.program_meme.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>xj.program_meme.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>xj.program_meme.program_id</code>.
     */
    @Override
    public UUID getProgramId() {
        return this.programId;
    }

    /**
     * Setter for <code>xj.program_meme.program_id</code>.
     */
    @Override
    public void setProgramId(UUID programId) {
        this.programId = programId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProgramMeme (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(programId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IProgramMeme from) {
        setId(from.getId());
        setName(from.getName());
        setProgramId(from.getProgramId());
    }

    @Override
    public <E extends IProgramMeme> E into(E into) {
        into.from(this);
        return into;
    }
}
