/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.tables.interfaces.IAccountUser;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountUser implements IAccountUser {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID userId;
    private UUID accountId;

    public AccountUser() {}

    public AccountUser(IAccountUser value) {
        this.id = value.getId();
        this.userId = value.getUserId();
        this.accountId = value.getAccountId();
    }

    public AccountUser(
        UUID id,
        UUID userId,
        UUID accountId
    ) {
        this.id = id;
        this.userId = userId;
        this.accountId = accountId;
    }

    /**
     * Getter for <code>xj.account_user.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.account_user.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.account_user.user_id</code>.
     */
    @Override
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>xj.account_user.user_id</code>.
     */
    @Override
    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>xj.account_user.account_id</code>.
     */
    @Override
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>xj.account_user.account_id</code>.
     */
    @Override
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountUser (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(accountId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAccountUser from) {
        setId(from.getId());
        setUserId(from.getUserId());
        setAccountId(from.getAccountId());
    }

    @Override
    public <E extends IAccountUser> E into(E into) {
        into.from(this);
        return into;
    }
}
