/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.tables.interfaces.IProgramVoiceTrack;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProgramVoiceTrack implements IProgramVoiceTrack {

    private static final long serialVersionUID = 1L;

    private UUID   id;
    private UUID   programId;
    private UUID   programVoiceId;
    private String name;
    private Float  order;

    public ProgramVoiceTrack() {}

    public ProgramVoiceTrack(IProgramVoiceTrack value) {
        this.id = value.getId();
        this.programId = value.getProgramId();
        this.programVoiceId = value.getProgramVoiceId();
        this.name = value.getName();
        this.order = value.getOrder();
    }

    public ProgramVoiceTrack(
        UUID   id,
        UUID   programId,
        UUID   programVoiceId,
        String name,
        Float  order
    ) {
        this.id = id;
        this.programId = programId;
        this.programVoiceId = programVoiceId;
        this.name = name;
        this.order = order;
    }

    /**
     * Getter for <code>xj.program_voice_track.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.program_voice_track.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.program_voice_track.program_id</code>.
     */
    @Override
    public UUID getProgramId() {
        return this.programId;
    }

    /**
     * Setter for <code>xj.program_voice_track.program_id</code>.
     */
    @Override
    public void setProgramId(UUID programId) {
        this.programId = programId;
    }

    /**
     * Getter for <code>xj.program_voice_track.program_voice_id</code>.
     */
    @Override
    public UUID getProgramVoiceId() {
        return this.programVoiceId;
    }

    /**
     * Setter for <code>xj.program_voice_track.program_voice_id</code>.
     */
    @Override
    public void setProgramVoiceId(UUID programVoiceId) {
        this.programVoiceId = programVoiceId;
    }

    /**
     * Getter for <code>xj.program_voice_track.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>xj.program_voice_track.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>xj.program_voice_track.order</code>.
     */
    @Override
    public Float getOrder() {
        return this.order;
    }

    /**
     * Setter for <code>xj.program_voice_track.order</code>.
     */
    @Override
    public void setOrder(Float order) {
        this.order = order;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProgramVoiceTrack (");

        sb.append(id);
        sb.append(", ").append(programId);
        sb.append(", ").append(programVoiceId);
        sb.append(", ").append(name);
        sb.append(", ").append(order);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IProgramVoiceTrack from) {
        setId(from.getId());
        setProgramId(from.getProgramId());
        setProgramVoiceId(from.getProgramVoiceId());
        setName(from.getName());
        setOrder(from.getOrder());
    }

    @Override
    public <E extends IProgramVoiceTrack> E into(E into) {
        into.from(this);
        return into;
    }
}
