/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.tables.interfaces.IProgramSequenceChord;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProgramSequenceChord implements IProgramSequenceChord {

    private static final long serialVersionUID = 1L;

    private UUID   id;
    private UUID   programId;
    private UUID   programSequenceId;
    private String name;
    private Double position;

    public ProgramSequenceChord() {}

    public ProgramSequenceChord(IProgramSequenceChord value) {
        this.id = value.getId();
        this.programId = value.getProgramId();
        this.programSequenceId = value.getProgramSequenceId();
        this.name = value.getName();
        this.position = value.getPosition();
    }

    public ProgramSequenceChord(
        UUID   id,
        UUID   programId,
        UUID   programSequenceId,
        String name,
        Double position
    ) {
        this.id = id;
        this.programId = programId;
        this.programSequenceId = programSequenceId;
        this.name = name;
        this.position = position;
    }

    /**
     * Getter for <code>xj.program_sequence_chord.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.program_sequence_chord.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.program_sequence_chord.program_id</code>.
     */
    @Override
    public UUID getProgramId() {
        return this.programId;
    }

    /**
     * Setter for <code>xj.program_sequence_chord.program_id</code>.
     */
    @Override
    public void setProgramId(UUID programId) {
        this.programId = programId;
    }

    /**
     * Getter for <code>xj.program_sequence_chord.program_sequence_id</code>.
     */
    @Override
    public UUID getProgramSequenceId() {
        return this.programSequenceId;
    }

    /**
     * Setter for <code>xj.program_sequence_chord.program_sequence_id</code>.
     */
    @Override
    public void setProgramSequenceId(UUID programSequenceId) {
        this.programSequenceId = programSequenceId;
    }

    /**
     * Getter for <code>xj.program_sequence_chord.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>xj.program_sequence_chord.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>xj.program_sequence_chord.position</code>.
     */
    @Override
    public Double getPosition() {
        return this.position;
    }

    /**
     * Setter for <code>xj.program_sequence_chord.position</code>.
     */
    @Override
    public void setPosition(Double position) {
        this.position = position;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProgramSequenceChord (");

        sb.append(id);
        sb.append(", ").append(programId);
        sb.append(", ").append(programSequenceId);
        sb.append(", ").append(name);
        sb.append(", ").append(position);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IProgramSequenceChord from) {
        setId(from.getId());
        setProgramId(from.getProgramId());
        setProgramSequenceId(from.getProgramSequenceId());
        setName(from.getName());
        setPosition(from.getPosition());
    }

    @Override
    public <E extends IProgramSequenceChord> E into(E into) {
        into.from(this);
        return into;
    }
}
