/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.tables.interfaces.IUserAuthToken;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAuthToken implements IUserAuthToken {

    private static final long serialVersionUID = 1L;

    private UUID   id;
    private UUID   userAuthId;
    private UUID   userId;
    private String accessToken;

    public UserAuthToken() {}

    public UserAuthToken(IUserAuthToken value) {
        this.id = value.getId();
        this.userAuthId = value.getUserAuthId();
        this.userId = value.getUserId();
        this.accessToken = value.getAccessToken();
    }

    public UserAuthToken(
        UUID   id,
        UUID   userAuthId,
        UUID   userId,
        String accessToken
    ) {
        this.id = id;
        this.userAuthId = userAuthId;
        this.userId = userId;
        this.accessToken = accessToken;
    }

    /**
     * Getter for <code>xj.user_auth_token.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.user_auth_token.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.user_auth_token.user_auth_id</code>.
     */
    @Override
    public UUID getUserAuthId() {
        return this.userAuthId;
    }

    /**
     * Setter for <code>xj.user_auth_token.user_auth_id</code>.
     */
    @Override
    public void setUserAuthId(UUID userAuthId) {
        this.userAuthId = userAuthId;
    }

    /**
     * Getter for <code>xj.user_auth_token.user_id</code>.
     */
    @Override
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>xj.user_auth_token.user_id</code>.
     */
    @Override
    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>xj.user_auth_token.access_token</code>.
     */
    @Override
    public String getAccessToken() {
        return this.accessToken;
    }

    /**
     * Setter for <code>xj.user_auth_token.access_token</code>.
     */
    @Override
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserAuthToken (");

        sb.append(id);
        sb.append(", ").append(userAuthId);
        sb.append(", ").append(userId);
        sb.append(", ").append(accessToken);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserAuthToken from) {
        setId(from.getId());
        setUserAuthId(from.getUserAuthId());
        setUserId(from.getUserId());
        setAccessToken(from.getAccessToken());
    }

    @Override
    public <E extends IUserAuthToken> E into(E into) {
        into.from(this);
        return into;
    }
}
