/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAccount extends Serializable {

    /**
     * Setter for <code>xj.account.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.account.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.account.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.account.name</code>.
     */
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IAccount
     */
    public void from(IAccount from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IAccount
     */
    public <E extends IAccount> E into(E into);
}
