/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ILibrary extends Serializable {

    /**
     * Setter for <code>xj.library.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.library.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.library.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.library.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>xj.library.account_id</code>.
     */
    public void setAccountId(UUID value);

    /**
     * Getter for <code>xj.library.account_id</code>.
     */
    public UUID getAccountId();

    /**
     * Setter for <code>xj.library.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value);

    /**
     * Getter for <code>xj.library.is_deleted</code>.
     */
    public Boolean getIsDeleted();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ILibrary
     */
    public void from(ILibrary from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ILibrary
     */
    public <E extends ILibrary> E into(E into);
}
