/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProgramSequenceBinding extends Serializable {

    /**
     * Setter for <code>xj.program_sequence_binding.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_binding.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.program_sequence_binding.program_id</code>.
     */
    public void setProgramId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_binding.program_id</code>.
     */
    public UUID getProgramId();

    /**
     * Setter for <code>xj.program_sequence_binding.program_sequence_id</code>.
     */
    public void setProgramSequenceId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_binding.program_sequence_id</code>.
     */
    public UUID getProgramSequenceId();

    /**
     * Setter for <code>xj.program_sequence_binding.offset</code>.
     */
    public void setOffset(Integer value);

    /**
     * Getter for <code>xj.program_sequence_binding.offset</code>.
     */
    public Integer getOffset();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IProgramSequenceBinding
     */
    public void from(IProgramSequenceBinding from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IProgramSequenceBinding
     */
    public <E extends IProgramSequenceBinding> E into(E into);
}
