/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProgramSequenceChord extends Serializable {

    /**
     * Setter for <code>xj.program_sequence_chord.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_chord.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.program_sequence_chord.program_id</code>.
     */
    public void setProgramId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_chord.program_id</code>.
     */
    public UUID getProgramId();

    /**
     * Setter for <code>xj.program_sequence_chord.program_sequence_id</code>.
     */
    public void setProgramSequenceId(UUID value);

    /**
     * Getter for <code>xj.program_sequence_chord.program_sequence_id</code>.
     */
    public UUID getProgramSequenceId();

    /**
     * Setter for <code>xj.program_sequence_chord.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.program_sequence_chord.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>xj.program_sequence_chord.position</code>.
     */
    public void setPosition(Double value);

    /**
     * Getter for <code>xj.program_sequence_chord.position</code>.
     */
    public Double getPosition();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IProgramSequenceChord
     */
    public void from(IProgramSequenceChord from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IProgramSequenceChord
     */
    public <E extends IProgramSequenceChord> E into(E into);
}
