/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUser extends Serializable {

    /**
     * Setter for <code>xj.user.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>xj.user.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>xj.user.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>xj.user.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>xj.user.email</code>.
     */
    public void setEmail(String value);

    /**
     * Getter for <code>xj.user.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>xj.user.avatar_url</code>.
     */
    public void setAvatarUrl(String value);

    /**
     * Getter for <code>xj.user.avatar_url</code>.
     */
    public String getAvatarUrl();

    /**
     * Setter for <code>xj.user.roles</code>.
     */
    public void setRoles(String value);

    /**
     * Getter for <code>xj.user.roles</code>.
     */
    public String getRoles();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUser
     */
    public void from(IUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUser
     */
    public <E extends IUser> E into(E into);
}
