#!/usr/bin/env bash

# Include common functions
. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/common/core

#
deps

#
step "Build UI\n"
cd ui || exit 1
npm install || exit 1
bower install || exit 1
ember build || exit 1
step_ok

#
finished_ok
