#!/usr/bin/env bash

# Include common functions
. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/common/core

# Expected JAR files
CORE_JAR=${PWD}/core/target/core-1.0-SNAPSHOT.jar
CRAFT_JAR=${PWD}/craft/target/craft-1.0-SNAPSHOT.jar
CLASSPATH=${CRAFT_JAR}:${CORE_JAR}
MAIN=io.outright.xj.craft.Main

# ensure platform is packaged
ensure_file ${CRAFT_JAR} "io.outright.xj.craft is packaged"
ensure_file ${CORE_JAR} "io.outright.xj.core is packaged"

# start up a craft
CMD="/usr/bin/java -classpath ${CLASSPATH} ${MAIN}"
step "${CMD}"
exec ${CMD}

#
finished_ok
