#!/usr/bin/env bash

# Include common functions
. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/common/core

#
deps

#
step "Clean Install (Maven) Java Project\n"
mvn clean install || exit 1
step_ok

#
finished_ok
