#!/usr/bin/env bash

# Include common functions
. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/common/core

# Title & Usage
APPS="hub craft ship"
TITLE="Release Version"
USAGE="
   Usage:
     cmd/release <version> <arguments...>

   <version> to release, as in 0.5.12
   <arguments...> (optional) passed to 'mvn package'
"

# Must specify <version> argument
VERSION=$1
if [ "${VERSION}" == "" ]; then
  printf "${RED}ERROR!${RESET} Please specify a version.\n"
  echo "${USAGE}"
  exit 1
fi
shift

# Version Arguments
MVN_ARGS=$@

# Zip file
ZIP_FILE=${PWD}/target/xj-release-${VERSION}.zip

#
step "Compile & Package Platform"
mvn clean package ${MVN_ARGS} || exit 1
step_ok

#
step "Clean target"
rm -fr ${PWD}/target
mkdir ${PWD}/target
step_ok

#
step "Add Procfile to target"
indent "$(cat Procfile)"
zip ${ZIP_FILE} Procfile
step_ok

#
step "Add artifacts to target"
for APP in ${APPS}; do
  zip -r ${ZIP_FILE} ${APP}/target/${APP}-1.0-SNAPSHOT.jar
done

#
finished_ok
