#!/usr/bin/env bash

# Include common functions
. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/common/core

# Must not have outstanding git changes
gitcheck ${PWD}

# Build Java Platform
cmd/package

# Build Static content
cmd/ui-build

# Package the release
cmd/release-package
