#!/usr/bin/env bash

bg_java_app() {
  APP=${1}
  JAR=/var/app/current/${APP}/target/${APP}-1.0-SNAPSHOT.jar
  if [ ! -e ${JAR} ]; then
    printf "\n\nCan't find ${JAR}!\nPlease package the build artifacts.\n\n"
    exit 1
  fi
  mkdir -p /var/log/${APP}
  java -jar ${JAR} &>/var/log/${APP}/${APP}.log &
  printf "Starting java: /var/app/current/${APP}/target/${APP}-1.0-SNAPSHOT.jar >>> /var/log/${APP}/${APP}.log\n"
}

#
printf "\n[xj:docker]\n"

#
chmod -R +r /var/app/current/ui/dist
service nginx start

# apps
bg_java_app hub
#bg_java_app craft
#bg_java_app ship

# Terminal
printf "\nLogging in...\n"
/bin/bash
