#!/usr/bin/env bash

bg_java_app() {
  APP=${1}
  mkdir -p /var/log/${APP}
  java -jar /var/app/current/${APP}/target/${APP}-1.0-SNAPSHOT.jar &>/var/log/${APP}/${APP}.log &
}

#
service nginx start

# apps
bg_java_app hub
#bg_java_app craft
#bg_java_app ship

# Terminal
/bin/bash
