#!/usr/bin/env bash

# Include common functions
. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/common/core

# Must not have outstanding git changes
gitcheck ${PWD}

# Build Java Platform
.z/package

# Build Static content
.z/ui-build

# Package the release
.z/release-package
