/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.tables.interfaces.IFlywaySchemaHistory;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlywaySchemaHistory implements IFlywaySchemaHistory {

    private static final long serialVersionUID = 1L;

    private Integer       installedRank;
    private String        version;
    private String        description;
    private String        type;
    private String        script;
    private Integer       checksum;
    private String        installedBy;
    private LocalDateTime installedOn;
    private Integer       executionTime;
    private Boolean       success;

    public FlywaySchemaHistory() {}

    public FlywaySchemaHistory(IFlywaySchemaHistory value) {
        this.installedRank = value.getInstalledRank();
        this.version = value.getVersion();
        this.description = value.getDescription();
        this.type = value.getType();
        this.script = value.getScript();
        this.checksum = value.getChecksum();
        this.installedBy = value.getInstalledBy();
        this.installedOn = value.getInstalledOn();
        this.executionTime = value.getExecutionTime();
        this.success = value.getSuccess();
    }

    public FlywaySchemaHistory(
        Integer       installedRank,
        String        version,
        String        description,
        String        type,
        String        script,
        Integer       checksum,
        String        installedBy,
        LocalDateTime installedOn,
        Integer       executionTime,
        Boolean       success
    ) {
        this.installedRank = installedRank;
        this.version = version;
        this.description = description;
        this.type = type;
        this.script = script;
        this.checksum = checksum;
        this.installedBy = installedBy;
        this.installedOn = installedOn;
        this.executionTime = executionTime;
        this.success = success;
    }

    /**
     * Getter for <code>xj.flyway_schema_history.installed_rank</code>.
     */
    @Override
    public Integer getInstalledRank() {
        return this.installedRank;
    }

    /**
     * Setter for <code>xj.flyway_schema_history.installed_rank</code>.
     */
    @Override
    public void setInstalledRank(Integer installedRank) {
        this.installedRank = installedRank;
    }

    /**
     * Getter for <code>xj.flyway_schema_history.version</code>.
     */
    @Override
    public String getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>xj.flyway_schema_history.version</code>.
     */
    @Override
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * Getter for <code>xj.flyway_schema_history.description</code>.
     */
    @Override
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>xj.flyway_schema_history.description</code>.
     */
    @Override
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>xj.flyway_schema_history.type</code>.
     */
    @Override
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>xj.flyway_schema_history.type</code>.
     */
    @Override
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>xj.flyway_schema_history.script</code>.
     */
    @Override
    public String getScript() {
        return this.script;
    }

    /**
     * Setter for <code>xj.flyway_schema_history.script</code>.
     */
    @Override
    public void setScript(String script) {
        this.script = script;
    }

    /**
     * Getter for <code>xj.flyway_schema_history.checksum</code>.
     */
    @Override
    public Integer getChecksum() {
        return this.checksum;
    }

    /**
     * Setter for <code>xj.flyway_schema_history.checksum</code>.
     */
    @Override
    public void setChecksum(Integer checksum) {
        this.checksum = checksum;
    }

    /**
     * Getter for <code>xj.flyway_schema_history.installed_by</code>.
     */
    @Override
    public String getInstalledBy() {
        return this.installedBy;
    }

    /**
     * Setter for <code>xj.flyway_schema_history.installed_by</code>.
     */
    @Override
    public void setInstalledBy(String installedBy) {
        this.installedBy = installedBy;
    }

    /**
     * Getter for <code>xj.flyway_schema_history.installed_on</code>.
     */
    @Override
    public LocalDateTime getInstalledOn() {
        return this.installedOn;
    }

    /**
     * Setter for <code>xj.flyway_schema_history.installed_on</code>.
     */
    @Override
    public void setInstalledOn(LocalDateTime installedOn) {
        this.installedOn = installedOn;
    }

    /**
     * Getter for <code>xj.flyway_schema_history.execution_time</code>.
     */
    @Override
    public Integer getExecutionTime() {
        return this.executionTime;
    }

    /**
     * Setter for <code>xj.flyway_schema_history.execution_time</code>.
     */
    @Override
    public void setExecutionTime(Integer executionTime) {
        this.executionTime = executionTime;
    }

    /**
     * Getter for <code>xj.flyway_schema_history.success</code>.
     */
    @Override
    public Boolean getSuccess() {
        return this.success;
    }

    /**
     * Setter for <code>xj.flyway_schema_history.success</code>.
     */
    @Override
    public void setSuccess(Boolean success) {
        this.success = success;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FlywaySchemaHistory (");

        sb.append(installedRank);
        sb.append(", ").append(version);
        sb.append(", ").append(description);
        sb.append(", ").append(type);
        sb.append(", ").append(script);
        sb.append(", ").append(checksum);
        sb.append(", ").append(installedBy);
        sb.append(", ").append(installedOn);
        sb.append(", ").append(executionTime);
        sb.append(", ").append(success);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IFlywaySchemaHistory from) {
        setInstalledRank(from.getInstalledRank());
        setVersion(from.getVersion());
        setDescription(from.getDescription());
        setType(from.getType());
        setScript(from.getScript());
        setChecksum(from.getChecksum());
        setInstalledBy(from.getInstalledBy());
        setInstalledOn(from.getInstalledOn());
        setExecutionTime(from.getExecutionTime());
        setSuccess(from.getSuccess());
    }

    @Override
    public <E extends IFlywaySchemaHistory> E into(E into) {
        into.from(this);
        return into;
    }
}
