/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.tables.interfaces.IProgramSequenceBinding;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProgramSequenceBinding implements IProgramSequenceBinding {

    private static final long serialVersionUID = 1L;

    private UUID    id;
    private UUID    programId;
    private UUID    programSequenceId;
    private Integer offset;

    public ProgramSequenceBinding() {}

    public ProgramSequenceBinding(IProgramSequenceBinding value) {
        this.id = value.getId();
        this.programId = value.getProgramId();
        this.programSequenceId = value.getProgramSequenceId();
        this.offset = value.getOffset();
    }

    public ProgramSequenceBinding(
        UUID    id,
        UUID    programId,
        UUID    programSequenceId,
        Integer offset
    ) {
        this.id = id;
        this.programId = programId;
        this.programSequenceId = programSequenceId;
        this.offset = offset;
    }

    /**
     * Getter for <code>xj.program_sequence_binding.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.program_sequence_binding.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.program_sequence_binding.program_id</code>.
     */
    @Override
    public UUID getProgramId() {
        return this.programId;
    }

    /**
     * Setter for <code>xj.program_sequence_binding.program_id</code>.
     */
    @Override
    public void setProgramId(UUID programId) {
        this.programId = programId;
    }

    /**
     * Getter for <code>xj.program_sequence_binding.program_sequence_id</code>.
     */
    @Override
    public UUID getProgramSequenceId() {
        return this.programSequenceId;
    }

    /**
     * Setter for <code>xj.program_sequence_binding.program_sequence_id</code>.
     */
    @Override
    public void setProgramSequenceId(UUID programSequenceId) {
        this.programSequenceId = programSequenceId;
    }

    /**
     * Getter for <code>xj.program_sequence_binding.offset</code>.
     */
    @Override
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * Setter for <code>xj.program_sequence_binding.offset</code>.
     */
    @Override
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProgramSequenceBinding (");

        sb.append(id);
        sb.append(", ").append(programId);
        sb.append(", ").append(programSequenceId);
        sb.append(", ").append(offset);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IProgramSequenceBinding from) {
        setId(from.getId());
        setProgramId(from.getProgramId());
        setProgramSequenceId(from.getProgramSequenceId());
        setOffset(from.getOffset());
    }

    @Override
    public <E extends IProgramSequenceBinding> E into(E into) {
        into.from(this);
        return into;
    }
}
