/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.enums.InstrumentType;
import io.xj.hub.tables.interfaces.IProgramVoice;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProgramVoice implements IProgramVoice {

    private static final long serialVersionUID = 1L;

    private UUID           id;
    private UUID           programId;
    private InstrumentType type;
    private String         name;
    private Float          order;

    public ProgramVoice() {}

    public ProgramVoice(IProgramVoice value) {
        this.id = value.getId();
        this.programId = value.getProgramId();
        this.type = value.getType();
        this.name = value.getName();
        this.order = value.getOrder();
    }

    public ProgramVoice(
        UUID           id,
        UUID           programId,
        InstrumentType type,
        String         name,
        Float          order
    ) {
        this.id = id;
        this.programId = programId;
        this.type = type;
        this.name = name;
        this.order = order;
    }

    /**
     * Getter for <code>xj.program_voice.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.program_voice.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.program_voice.program_id</code>.
     */
    @Override
    public UUID getProgramId() {
        return this.programId;
    }

    /**
     * Setter for <code>xj.program_voice.program_id</code>.
     */
    @Override
    public void setProgramId(UUID programId) {
        this.programId = programId;
    }

    /**
     * Getter for <code>xj.program_voice.type</code>.
     */
    @Override
    public InstrumentType getType() {
        return this.type;
    }

    /**
     * Setter for <code>xj.program_voice.type</code>.
     */
    @Override
    public void setType(InstrumentType type) {
        this.type = type;
    }

    /**
     * Getter for <code>xj.program_voice.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>xj.program_voice.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>xj.program_voice.order</code>.
     */
    @Override
    public Float getOrder() {
        return this.order;
    }

    /**
     * Setter for <code>xj.program_voice.order</code>.
     */
    @Override
    public void setOrder(Float order) {
        this.order = order;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProgramVoice (");

        sb.append(id);
        sb.append(", ").append(programId);
        sb.append(", ").append(type);
        sb.append(", ").append(name);
        sb.append(", ").append(order);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IProgramVoice from) {
        setId(from.getId());
        setProgramId(from.getProgramId());
        setType(from.getType());
        setName(from.getName());
        setOrder(from.getOrder());
    }

    @Override
    public <E extends IProgramVoice> E into(E into) {
        into.from(this);
        return into;
    }
}
