/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.enums.TemplateType;
import io.xj.hub.tables.interfaces.ITemplate;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Template implements ITemplate {

    private static final long serialVersionUID = 1L;

    private UUID         id;
    private UUID         accountId;
    private String       name;
    private String       config;
    private String       shipKey;
    private TemplateType type;
    private Boolean      isDeleted;

    public Template() {}

    public Template(ITemplate value) {
        this.id = value.getId();
        this.accountId = value.getAccountId();
        this.name = value.getName();
        this.config = value.getConfig();
        this.shipKey = value.getShipKey();
        this.type = value.getType();
        this.isDeleted = value.getIsDeleted();
    }

    public Template(
        UUID         id,
        UUID         accountId,
        String       name,
        String       config,
        String       shipKey,
        TemplateType type,
        Boolean      isDeleted
    ) {
        this.id = id;
        this.accountId = accountId;
        this.name = name;
        this.config = config;
        this.shipKey = shipKey;
        this.type = type;
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>xj.template.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.template.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.template.account_id</code>.
     */
    @Override
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>xj.template.account_id</code>.
     */
    @Override
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>xj.template.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>xj.template.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>xj.template.config</code>.
     */
    @Override
    public String getConfig() {
        return this.config;
    }

    /**
     * Setter for <code>xj.template.config</code>.
     */
    @Override
    public void setConfig(String config) {
        this.config = config;
    }

    /**
     * Getter for <code>xj.template.ship_key</code>.
     */
    @Override
    public String getShipKey() {
        return this.shipKey;
    }

    /**
     * Setter for <code>xj.template.ship_key</code>.
     */
    @Override
    public void setShipKey(String shipKey) {
        this.shipKey = shipKey;
    }

    /**
     * Getter for <code>xj.template.type</code>.
     */
    @Override
    public TemplateType getType() {
        return this.type;
    }

    /**
     * Setter for <code>xj.template.type</code>.
     */
    @Override
    public void setType(TemplateType type) {
        this.type = type;
    }

    /**
     * Getter for <code>xj.template.is_deleted</code>.
     */
    @Override
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>xj.template.is_deleted</code>.
     */
    @Override
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Template (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(name);
        sb.append(", ").append(config);
        sb.append(", ").append(shipKey);
        sb.append(", ").append(type);
        sb.append(", ").append(isDeleted);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITemplate from) {
        setId(from.getId());
        setAccountId(from.getAccountId());
        setName(from.getName());
        setConfig(from.getConfig());
        setShipKey(from.getShipKey());
        setType(from.getType());
        setIsDeleted(from.getIsDeleted());
    }

    @Override
    public <E extends ITemplate> E into(E into) {
        into.from(this);
        return into;
    }
}
