/*
 * This file is generated by jOOQ.
 */
package io.xj.hub.tables.pojos;


import io.xj.hub.tables.interfaces.IUser;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements IUser {

    private static final long serialVersionUID = 1L;

    private UUID   id;
    private String name;
    private String email;
    private String avatarUrl;
    private String roles;

    public User() {}

    public User(IUser value) {
        this.id = value.getId();
        this.name = value.getName();
        this.email = value.getEmail();
        this.avatarUrl = value.getAvatarUrl();
        this.roles = value.getRoles();
    }

    public User(
        UUID   id,
        String name,
        String email,
        String avatarUrl,
        String roles
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.avatarUrl = avatarUrl;
        this.roles = roles;
    }

    /**
     * Getter for <code>xj.user.id</code>.
     */
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>xj.user.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>xj.user.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>xj.user.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>xj.user.email</code>.
     */
    @Override
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>xj.user.email</code>.
     */
    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>xj.user.avatar_url</code>.
     */
    @Override
    public String getAvatarUrl() {
        return this.avatarUrl;
    }

    /**
     * Setter for <code>xj.user.avatar_url</code>.
     */
    @Override
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * Getter for <code>xj.user.roles</code>.
     */
    @Override
    public String getRoles() {
        return this.roles;
    }

    /**
     * Setter for <code>xj.user.roles</code>.
     */
    @Override
    public void setRoles(String roles) {
        this.roles = roles;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(avatarUrl);
        sb.append(", ").append(roles);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUser from) {
        setId(from.getId());
        setName(from.getName());
        setEmail(from.getEmail());
        setAvatarUrl(from.getAvatarUrl());
        setRoles(from.getRoles());
    }

    @Override
    public <E extends IUser> E into(E into) {
        into.from(this);
        return into;
    }
}
