name: Engine Distro

on:
  push:
    tags: [ '*' ]

jobs:
  nothing_left_todo:
    name: Nothing Left TODO
    env:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Nothing left TODO
        run: .github/nothing_left_todo.sh engine

  verify_version_number:
    needs: nothing_left_todo
    name: Verify Version Number
    env:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
    runs-on: ubuntu-latest
    outputs:
      workstation-version: ${{ steps.get-workstation-version.outputs.version }}
      engine-version: ${{ steps.get-engine-version.outputs.version }}
      engine-docs-version: ${{ steps.get-engine-docs-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get workstation version
        id: get-workstation-version
        working-directory: workstation/
        run: |
          VERSION=$(grep "version=" gradle.properties | sed -n -e 's/^.*version=//p')
          if [ -z "$VERSION" ]; then
            echo "Version number not found!"
            exit 1
          fi
          echo "Workstation Version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check workstation version vs tag name
        run: |
          TAG_NAME=${{ github.ref_name }}
          VERSION=${{ steps.get-workstation-version.outputs.version }}
          if [ "$TAG_NAME" != "v$VERSION" ]; then
            echo "gradle.properties version number '$VERSION' implies tag name 'v$VERSION' but instead found '$TAG_NAME'!"
            exit 1
          fi

      - name: Get engine version
        id: get-engine-version
        working-directory: engine/
        run: |
          VERSION=$(grep " VERSION " CMakeLists.txt | sed -n -e 's/^.*VERSION //p')
          if [ -z "$VERSION" ]; then
            echo "Version number not found!"
            exit 1
          fi
          echo "Engine Version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check workstation version vs engine version
        run: |
          WORKSTATION_VERSION=${{ steps.get-workstation-version.outputs.version }}
          ENGINE_VERSION=${{ steps.get-engine-version.outputs.version }}
          if [ "$WORKSTATION_VERSION" != "$ENGINE_VERSION" ]; then
            echo "Workstation version '$WORKSTATION_VERSION' does not match engine version '$ENGINE_VERSION'!"
            exit 1
          fi


  test_and_ship_static_library:
    needs: verify_version_number
    env:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
    name: Test & Ship Library [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    permissions: write-all
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-13, macos-14, windows-latest ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        working-directory: engine/
        run: |
          choco install cmake

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        working-directory: engine/
        run: |
          sudo apt-get install -y cmake

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        working-directory: engine/
        run: |
          brew install cmake

      - name: Build
        working-directory: engine/
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Test (Windows)
        if: runner.os == 'Windows'
        working-directory: engine/
        run: |
          cd build/test
          .\Debug\xjmusic_test.exe

      - name: Test (macOS/Linux)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        working-directory: engine/
        run: |
          cd build
          ctest --verbose

      - name: Build the Static Library
        working-directory: engine/
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make
          cp libxjmusic.a xjmusic-v${{ needs.verify_version_number.outputs.version }}.lib

      - name: Compress .lib file (macOS/Intel)
        if: runner.os == 'macOS' && runner.arch == 'X64'
        working-directory: engine/
        run: |
          cd build/
          zip xjmusic-v${{ needs.verify_version_number.outputs.version }}-macos-intel.lib.zip xjmusic-v${{ needs.verify_version_number.outputs.version }}.lib

      - name: Upload to release (macOS/Intel)
        if: runner.os == 'macOS' && runner.arch == 'X64'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: engine/build/xjmusic-v${{ needs.verify_version_number.outputs.version }}-macos-intel.lib.zip
          asset_name: xjmusic-v${{ needs.verify_version_number.outputs.version }}-macos-intel.lib.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload to Amazon S3 (macOS/Intel)
        if: runner.os == 'macOS' && runner.arch == 'X64'
        run:
          aws s3 cp engine/build/xjmusic-v${{ needs.verify_version_number.outputs.version }}-macos-intel.lib.zip s3://${{ secrets.AWS_S3_BUCKET }}/

      - name: Compress .lib file (macOS/Silicon)
        if: runner.os == 'macOS' && runner.arch == 'ARM64'
        working-directory: engine/
        run: |
          cd build/
          zip xjmusic-v${{ needs.verify_version_number.outputs.version }}-macos-silicon.lib.zip xjmusic-v${{ needs.verify_version_number.outputs.version }}.lib

      - name: Upload to release (macOS/Silicon)
        if: runner.os == 'macOS' && runner.arch == 'ARM64'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: engine/build/xjmusic-v${{ needs.verify_version_number.outputs.version }}-macos-silicon.lib.zip
          asset_name: xjmusic-v${{ needs.verify_version_number.outputs.version }}-macos-silicon.lib.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload to Amazon S3 (macOS/Silicon)
        if: runner.os == 'macOS' && runner.arch == 'ARM64'
        run:
          aws s3 cp engine/build/xjmusic-v${{ needs.verify_version_number.outputs.version }}-macos-silicon.lib.zip s3://${{ secrets.AWS_S3_BUCKET }}/

      - name: Compress .lib file for Windows
        if: runner.os == 'Windows'
        working-directory: engine/
        run: |
          cd build/
          Compress-Archive -Path xjmusic-v${{ needs.verify_version_number.outputs.version }}.lib -DestinationPath xjmusic-v${{ needs.verify_version_number.outputs.version }}-windows.lib.zip

      - name: Upload to release (Windows)
        if: runner.os == 'Windows'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: engine/build/xjmusic-v${{ needs.verify_version_number.outputs.version }}-windows.lib.zip
          asset_name: xjmusic-v${{ needs.verify_version_number.outputs.version }}-windows.lib.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload to Amazon S3 (Windows)
        if: runner.os == 'Windows'
        run:
          aws s3 cp engine/build/xjmusic-v${{ needs.verify_version_number.outputs.version }}-windows.lib.zip s3://${{ secrets.AWS_S3_BUCKET }}/

      - name: Compress .lib file for Linux
        if: runner.os == 'Linux'
        working-directory: engine/
        run: |
          cd build/
          tar -czvf xjmusic-v${{ needs.verify_version_number.outputs.version }}-linux.lib.tar.gz xjmusic-v${{ needs.verify_version_number.outputs.version }}.lib

      - name: Upload to release (Linux)
        if: runner.os == 'Linux'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: engine/build/xjmusic-v${{ needs.verify_version_number.outputs.version }}-linux.lib.tar.gz
          asset_name: xjmusic-v${{ needs.verify_version_number.outputs.version }}-linux.lib.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload to Amazon S3 (Linux)
        if: runner.os == 'Linux'
        run:
          aws s3 cp engine/build/xjmusic-v${{ needs.verify_version_number.outputs.version }}-linux.lib.tar.gz s3://${{ secrets.AWS_S3_BUCKET }}/
