name: "Pull Request"

on:
  pull_request:
    # Ignore branches having their own workflows
    branches-ignore:
      - 'prod'

jobs:
  PullRequest:
    env:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
      JAVA_VERSION: 21
    name: Gradle
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: burrunan/gradle-cache-action@v1
        name: Cache Gradle
        with:
          job-id: jdk${{ env.JAVA_VERSION }}

      - name: Setup JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-package: jdk

      - name: Build & Run Tests
        id: test
        run: "./gradlew --info --no-daemon build test"
        continue-on-error: false

      - name: Nothing left TODO
        run: .github/nothing_left_todo.sh
