name: "Pull Request"

on:
  pull_request:
    # Ignore branches having their own workflows
    branches-ignore:
      - 'prod'

jobs:
  PullRequest:
    env:
      CI_BOT_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      CI_BOT_USERNAME: ${{ secrets.CI_BOT_USERNAME }}
    name: Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: burrunan/gradle-cache-action@v1
        name: Cache Gradle
        with:
          job-id: jdk17

      - name: Install and cache system packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ffmpeg gpac postgresql-client
          version: 1.0

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          java-package: jdk

      - name: Build & Run Tests
        id: test
        run: "./gradlew --info --no-daemon build test"
        continue-on-error: false

      - name: Nothing left TODO
        run: .github/nothing_left_todo.sh
