name: Workstation PR

on:
  pull_request:
    paths:
      - workstation/**

jobs:
  build_and_test:
    env:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
    name: Build & Test [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    permissions: read-all
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-13, macos-14, windows-latest ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: burrunan/gradle-cache-action@v1
        name: Cache Gradle
        with:
          job-id: workstation-tests-${{ matrix.os }}

      - name: Set up JDK17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          java-package: jdk

      - name: Build & Run Tests
        id: test
        working-directory: workstation/
        run: "./gradlew --info --no-daemon build test"
        continue-on-error: false


  nothing_left_todo:
    needs: build_and_test
    env:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
    name: Nothing Left TODO
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Nothing left TODO
        run: .github/nothing_left_todo.sh
